name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: demoappdevopscasual
  AZURE_CONTAINER_REGISTRY: demoappdevopscasualacr.azurecr.io
  IMAGE_NAME: azure-devops-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: az acr login --name demoappdevopscasualacr

    - name: Build and push Docker image
      run: |
        docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest ./app
        docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest

    - name: Deploy to Web App
      run: |
        az webapp config container set \
          --name $AZURE_WEBAPP_NAME \
          --resource-group devops-rg-north \
          --docker-custom-image-name $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest \
          --docker-registry-server-url https://$AZURE_CONTAINER_REGISTRY
